# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-24 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=30)),
                ('price', models.SmallIntegerField()),
                ('reason', models.CharField(max_length=10)),
                ('channel', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('result', models.SmallIntegerField()),
                ('charge_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('sent_status', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('effective_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_keyword', models.CharField(max_length=30)),
                ('unreg_keyword', models.CharField(max_length=30)),
                ('service_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=30)),
                ('request_type', models.SmallIntegerField()),
                ('channel', models.CharField(max_length=20)),
                ('result', models.SmallIntegerField()),
                ('message', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=30)),
                ('service_number', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=2)),
                ('received_time', models.DateTimeField(auto_now=True)),
                ('responsed_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=30)),
                ('service_number', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=1)),
                ('num_of_sm', models.SmallIntegerField()),
                ('num_of_receipt', models.SmallIntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('effective_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='responses', to='service.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name=b'Service Code')),
                ('package_code', models.CharField(max_length=50, verbose_name=b'Package Code')),
                ('name', models.CharField(max_length=200, verbose_name=b'Service Name')),
                ('schedule', models.CharField(max_length=100)),
                ('price', models.SmallIntegerField()),
                ('period_length', models.SmallIntegerField()),
                ('free_length', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.BigIntegerField()),
                ('msisdn', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expired_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('type', models.TextField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=2, verbose_name=b'System ID')),
                ('code', models.CharField(max_length=50, verbose_name=b'System Code')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='responses', to='service.Service'),
        ),
        migrations.AddField(
            model_name='response',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='responses', to='service.System'),
        ),
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='requests', to='service.Service'),
        ),
        migrations.AddField(
            model_name='request',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='requests', to='service.System'),
        ),
        migrations.AddField(
            model_name='registerlog',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='register_logs', to='service.Service'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='keywords', to='service.Service'),
        ),
        migrations.AddField(
            model_name='content',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='contents', to='service.Service'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='cdrs', to='service.Service'),
        ),
    ]
